# Generated by Django 5.0.4 on 2024-04-18 19:47

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_audio_note_delete_voicenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(default=notes.models.Audio.generate_random_name, max_length=255),
        ),
    ]
